### ISSUE TITLE
Manually checking results when testing APs

### ISSUE THREAD

**Issue by vanhoefm** [vanhoefm/fragattacks#11]
Question received by email: "My test case is testing AP’s (I do not test clients, just AP’s for the moment) and I wanted to ask for clarification when I'm instructed to “manually check results”. I believe this has to do with using tcpdump to see if EAPOL keys are being sent back and forth. When I look at the example pcaps provided within your github I can see there is Key exchange 1 of 4 all the way to 4 of 4. However in my test case when I run tcpdump on wlan1mon (the card sending the ping attacks) I only see EAPOL key 1 of 4 and 3 of 4."

**Comment by vanhoefm** [comment]
You have to run tcpdump **on the device being tested**. Note that you can generally [avoid using tcpdump on APs](https://github.com/vanhoefm/fragattacks#id-avoiding-tcpdump-aps) with the proper setup.

**Comment by PenguinOBEY** [comment]
I was having that exact same problem.
So the solution to that would be --bcast-dst
Now when using that flag should I provide the IP of the other device that is connected to the AP being tested? Or just run tcpdump on eth0
Another question would be for the device doing the sniffing should that be using wireless connectivity or using an ethernet cable?
E.g.
ping I,P --bcast-ra --bcast-dst <IP>
-OR-
ping I,P --bcast-ra --bcast-dst

**Comment by vanhoefm** [comment]
The parameter `--bcast-dst` doesn't accept an argument. There is no need to manually specify an IP address, meaning using `--ip` or `--peerip` is not needed here. Using alid IP addresses is only important when _not_ using tcpdump.
