### ISSUE TITLE
Script output "The 4-way handshake has timed out for an unknown reason"

### ISSUE THREAD

**Issue by sumukh5** [vanhoefm/fragattacks#13]
For some commands, example ping I,E,F,AE, i am getting "The 4-way handshake has timed out for an unknown reason",

**Comment by vanhoefm** [comment]
It could be that the device under test only accepts plaintext EAPOL frames. Try some of the [variants](https://github.com/vanhoefm/fragattacks#id-extended-mixedkey) to see if they work. If you keep getting this message you can assume that the device is not vulnerable.

To also repeat the paper: "we recommend to only consider a device secure if there are explicit checks in the code to prevent attacks and if practical tests show it is indeed not vulnerable". So if you have access to the source code you should audit it as well (this unfortunately will require an expert understanding of the code).
