### ISSUE TITLE
CTRL-EVENT-NETWORK-NOT-FOUND

### ISSUE THREAD

**Issue by D3adP3nguin** [vanhoefm/fragattacks#18]
I have been using the Live image OS for multiple AP testing and it has been working great. However all of a sudden the tool started getting hung up on "Successfully initialized WPA supplicant", so I decided to turn on debugging to see what could be causing this issue. the debugging logs show me that "CTRL-EVENT-NETWORK-NOT-FOUND" however when I manually scroll through the debug logs I can see the SSID of the device I set up in the client.conf file (and made sure to rerun ./build.sh) I'm not sure what could be causing this problem. 
I am using a Alfa AWUS036NHA ; and I have been using this device for my previous 6 tests and it has worked fine, and now suddenly I'm starting to get this error. Any help would be greatly appreciated.

**Comment by vanhoefm** [comment]
Can you show the full debug output? Some things to look out for:

1. Make sure you properly entered the SSID. Look at the debug output to check whether the network is loaded properly.
2. Are you trying to connect to a hidden network? If so, add the `scan_ssid=1` parameter to `client.conf` ([see example](https://www.raspberrypi.org/forums/viewtopic.php?t=25104)).

**Comment by D3adP3nguin** [comment]
[debug.txt](https://github.com/vanhoefm/fragattacks/files/6639509/debug.txt)

This is the latest test. I used the scan_ssid=1 parameter in the client.conf and reran ./build.sh to confirm changes. I also did the same test on the 2.4Ghz channel and it is not working either.

**Comment by D3adP3nguin** [comment]
I switched back to an old device and the test case works (I just changed the client.conf file) I think it may be an issue with the AP itself. If you have any thoughts please let me know. Thank you for the continued support.

**Comment by D3adP3nguin** [comment]
I reran the test again and this time TESTNET was actually seen by the device but gets the following message in the debug output:

wlan1mon: BSS: Remove id 6 BSSID 58:ef:68:5f:2d:31 SSID 'TESNET' due to wpa_bss_flush

**Comment by vanhoefm** [comment]
Looks like the network name advertised by the AP is 'TESNET' but in `client.conf` you included the network 'TESTNET_5G'. Notice that the network advertised by the AP seems to be missing the letter 'T' in the middle. Additionally, the network specified in your `client.conf` shouldn't include the '_5G' suffix (unless your AP also includes it).

**Comment by D3adP3nguin** [comment]
I attempted the test on both the 2.4ghz (TESTNET) and the 5ghz (TESTNET_5G) I just sent the log for the 5Ghz test.

**Comment by D3adP3nguin** [comment]
[debug_Guest_htdisabled.txt](https://github.com/vanhoefm/fragattacks/files/6640268/debug_Guest_htdisabled.txt)
[debug_Guest.txt](https://github.com/vanhoefm/fragattacks/files/6640269/debug_Guest.txt)
[debug3.txt](https://github.com/vanhoefm/fragattacks/files/6640270/debug3.txt)

here are a few more debug logs. 
I attempted to test the Guest SSID but that didnt connect either. Modified the ht_disabled settings that didnt help either... I triple check the SSID and PSK in the client.conf file everytime I iknow its not that.

**Comment by D3adP3nguin** [comment]
Thank you very much
