### ISSUE TITLE
Environment configuration issues

### ISSUE THREAD

**Issue by xiaodong-2** [vanhoefm/fragattacks#19]
hi everyone
I followed the instructions to configure my test environment using the installation, but the network card driver you provided,Failed to run successfully on **_Kali linux (5.10.0-kali7-amd64 #1 SMP Debian 5.10.28-akali (21-04-12) x86_64 GNU/Linux)_**
The system prompts the missing file, I did not find the corresponding source file on the network, also tries to update the kernel version, but still cannot run.
By the way: do you only support the types of WiFi described in the guide?

**_The failure log is as follows:_**

(ro0:0ali)-[~/fragattacks-drivers58-zy install kernel-headers-$(voot -r)
Command "root' not found, did you mean:
command"foot" from deb foot
command'rootv'from deb xawtv
command'prootfrom deb proot
command "toot' from deb toot
Try: apt install <deb name>
Command "yum' not found, did you mean:
command 'zum' from deb perforate
command "yum4" from deb nextgen-yum4
command'uum'from deb freewnn-jserver
'num'commandfrom deb quickcal
command "sum' from deb coreutils
Try: apt install <deb name>
ro0t0kali)-[~/fragattacks-drivers58
make defconfig-wifi                           127
Your kernel headers are incomplete/not installed.Please install kernel headers, including a .configfile or use the KLIB/KLIB_BUILD make variables toset the kernel to build against, esg.
make KLIB=/lib/modules/3.1.7/
to compile/install for the installed kernel 3.1.7(that isn't currently running.)
make:[Makefile:41: defconfig-wifi] Error 

~ -(venv -(root O lkali)-[~/fragattacks/reseac

L# ./fragattack.py 192.168.1.9 ping

[04:47:01] This is FragAttack version 1.3.

[04:47:01] WARNING: Unable to check whether you are using patched drivers . Traceback (most recent call last ):

File "/root/fragattacks/research fraginternals.py" , line[766, in configure_interfaces

scapy.arch.get if index(self .nic. mon)

File /root/fragattacks/research/env/l/ .9/site-packages/scapya h/linux.py", line 380, in get if index

return int(struct.unpack("I", get. if(iff, SIOCGIFINDEX)[16:0])[0

file "/root/fragattacks/research .9/site-packages/scapy/arc h/ common.py", line 59, in get_ if

ifreq ะ ioctl(sck, cmd, struct. pack("16s16x" , iff. encode( "utf8" )))

SError: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

file "/root/fragattacks/research ./fragattack.py", line 267, in <module> daemon. run( )

file "/root/fragattacks/ research/ fraginternals.py" line 889, in run

self .conf igure_ interfaces )

File "/root/fragattacks/ research/fraginternals.py" line 769, in configureinterfaces

subprocess ·check output(["iw", self.nic iface, "interface". "add", self.n c_ mon, " type" , " monitor"])

file "/usr/lib/python3 ·9/subprocess.py" line 424, in check output

return run( *popenargs, stdout-PIPE , timeout=timeout, check=True,

file "/usr/lib/python3. 9/subprocess ·py", line 528, in run

raise CalledProcessError retcode, process.args 7

subprocess . CalledProcessError: Command '['iw', 192.168.1. interface'. 'a dd' , , mon192.168.1.9', 'type', ' monitor'J returned non-zero exit status i. [04:47:01] Closing daemon and cleaning up ...

this is FragAttack version 1.3
WARNING:Unabled to check whether you are using patched drivers.

**Comment by vanhoefm** [comment]
> (ro0:0ali)-[~/fragattacks-drivers58-zy install kernel-headers-$(voot -r) Command "root' not found, did you mean: command"foot" from deb foot command'rootv'from deb xawtv command'prootfrom deb proot command "toot' from deb toot Try: apt install Command "yum' not found, did you mean: command 'zum' from deb perforate command "yum4" from deb nextgen-yum4 command'uum'from deb freewnn-jserver 'num'commandfrom deb quickcal command "sum' from deb coreutils Try: apt install ro0t0kali)-[~/fragattacks-drivers58

How much experience do you have using a terminal / command line? You aren't following the instructions correctly. Please follow all steps and show exactly what you are trying to execute. It may be better to use the Live USB image if you are not familiar with Linux.

**Comment by xiaodong-2** [comment]
Dear Creator:
Thank you for your prompt reply and advice, I'm really not a great Linux player, but here's my puzzle: I followed the instructions to the letter, including the guidelines for firewalls and Python3 libraries.This only fails when installing the patch driver, and fails when running make defconfig-wifi.
I downloaded kernel-headers according to the prompts, but I could not find the required source file on the network.Please guide me on how to properly install and start this script.

Thank you very much.


From: vanhoefm ***@***.***>
Sent: 2021年6月15日 18:25
To: vanhoefm/fragattacks ***@***.***>
Cc: Guo, Xiedong (EXT-NSB - CN/Shanghai) ***@***.***>; Author ***@***.***>
Subject: [Suspected Marketing Mail] Re: [vanhoefm/fragattacks] Environment configuration issues (#19)


(ro0:0ali)-[/fragattacks-drivers58-zy install kernel-headers-$(voot -r) Command "root' not found, did you mean: command"foot" from deb foot command'rootv'from deb xawtv command'prootfrom deb proot command "toot' from deb toot Try: apt install Command "yum' not found, did you mean: command 'zum' from deb perforate command "yum4" from deb nextgen-yum4 command'uum'from deb freewnn-jserver 'num'commandfrom deb quickcal command "sum' from deb coreutils Try: apt install ro0t0kali)-[/fragattacks-drivers58

How much experience do you have using a terminal / command line? You aren't following the instructions correctly. Please follow all steps and show exactly what you are trying to execute. It may be better to use the Live USB image if you are not familiar with Linux.

**Comment by xiaodong-2** [comment]
Dear Creator:
      I perform to (git clone fragattacks - drivers58 https://github.com/vanhoefm/fragattacks-drivers58.git this step, I can't use community account, to get to the dervers.Please help me.
thanks.

**Comment by vanhoefm** [comment]
Unfortunately, it will be best to learn more about the Linux terminal first. This tool assumes sufficient knowledge of Linux.
