### ISSUE TITLE
Alfa AWUS036ACM - Ubuntu VM not detecting this device

### ISSUE THREAD

**Issue by sumukh5** [vanhoefm/fragattacks#22]
I purchased Alfa AWUS036ACM device and my laptop is Dell precision 7510, this laptop has 4 USB 3.0 ports and when i connect AWUS036ACM to Ubuntu VM, the device is not getting detected, lsusb is not listing this device and i tried manually loading the driver "sudo modprobe mt76x2u" but no luck, any suggestions?

![error](https://user-images.githubusercontent.com/25736983/123751328-3f813c80-d8d5-11eb-83a7-b5f48a474473.png)

**Comment by vanhoefm** [comment]
Since the device is not shown under `lsusb` there might be a configuration issue in the Virtual Machine (that might also explain the warning by VirtualBox). In the VM, in Settings > USB, did you enable "USB 3.0 (xHCI) Controller"?

**Comment by Ma5onic** [comment]
@sumukh5, I have noticed that you are you are using vmware and I have had many issues in the past when trying to connect wireless dongles in monitor mode. 
If you go to your VM settings in the hardware tab > usb controller > USB Compatibility
I only see usb 1.1, 2.0 & 3.1. There is no usb 3.0, so you may need to use usb 2.0. if 3.1 is not supported on your device 
![image](https://user-images.githubusercontent.com/18509613/127040625-242fa850-5a9c-4b2d-b90c-ed3cd536df78.png)

**Comment by D3adP3nguin** [comment]
Previously I have been using a AWUS036NHA and I wanted to switch to testing 5Ghz channels so I got a AWUS036ACM. The provided ubuntu os was able to detect my device and I was able to set it into monitor. mode. However when trying to run a simple command such as `./fragattack.py wlan0mon pin` I get the following error: 
```
Unable to connect to control interface. Did hostap/wpasupplicant start properly?
Try recompiling then using ./build.sh and doucle-check client.conf and hostapd.conf
```

Now I have been doing these tests for a while so Im very confident in my setup however just when swapping the cards from the NHA to the ACM this error occurs. Any thoughts or fixes?

**Comment by D3adP3nguin** [comment]
Im using the liveusb image and when using the live ubuntu image the wireless card is detected. However trying to use this wireless card with ./fragattack.py causes an error and then it also causes my device to crash.
Within your VM have you been able to get the AWES036ACM to work with the fragattack.py script? 
It worked with the test-injection.py script but not with the actual fragattack.py script

**Comment by vanhoefm** [comment]
I've also had some reliability issues with the AWUS036ACM. I don't know the exact cause behind it, sometimes it helped to plug it into another USB port (in particular using an older USB 2.0 port).

**Comment by debrunet** [comment]
My AWUS036ACM also did not show up in any Linux VM, but worked fine in a Windows VM. With `lspci` it was never listed. It showed up by changing USB compatibility from 2.0 to 3.1 in VMware Fusion.
<img width="752" alt="png" src="https://user-images.githubusercontent.com/61621711/145033071-c6368f69-f35d-4a05-b795-baac9e75edb0.png">

**Comment by bankhans** [comment]
Same problem with VirtualBox on Windows, Ubuntu Desktop as guest. No passthrough possible. Other usb Wifi stick work fine.
