### ISSUE TITLE
Getting error CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN

### ISSUE THREAD

**Issue by sumukh5** [vanhoefm/fragattacks#23]
Getting attached error while testing my setup with 'ping', SSID is not hidden and i am sure that my client.conf has proper WAP SSID and password.
![error](https://user-images.githubusercontent.com/25736983/123811720-20a09b80-d911-11eb-94be-3c3b8d502f2a.png)

**Comment by sumukh5** [comment]
this is resolved, use "iw reg set US" and re-run the command.

**Comment by vanhoefm** [comment]
This looked more like a warning from `wpa_supplicant`. Thanks for the info on how to nevertheless avoid it.
