### ISSUE TITLE
Retransmitting DHCP message

### ISSUE THREAD

**Issue by D3adP3nguin** [vanhoefm/fragattacks#25]
When using the test tool in ap mode (--ap) I am getting an error after a client device connects.
After `Action.Connected` the tool is consistently outputting `Retransmitting DHCP message`. Any thoughts as to what can be causing this? I also used the flag --stay-up. 
The exact command was `./fragattack.py wlan1mon --ap ping --stay-up`
I also tried  `./fragattack.py wlan1mon --ap ping --stay-up --no-dhcp` and that still got the consistent output of  `Retransmitting DHCP message`

**Comment by vanhoefm** [comment]
Why is the name of your interface `wlan1mon` and not `wlan1`?

Can you show the full debug output and perhaps also a network capture? I'm assuming you didn't make any changes to the code itself?

**Comment by D3adP3nguin** [comment]
It's waln1mon because I used 'ip link set name' to change it from some crazy manufacturer name and I was doing regular FnF testing before. But it isn't in monitor mode or else the --ap flag wouldn't work. 
I'll try to get those debug logs to you ASAP.

**Comment by D3adP3nguin** [comment]
So i got the DHCP retransmitting error to go away by using a different network at work. However, I still have a question when testing a device in client mode (meaning the FnF machine is running the --ap flag) 

A quick summary of the test network map: 
FnF machine running off USB: all CMDs are appended with the --ap mode 
Windows10 machine: The USB dongle that is being tested is controlled from there; also Wireshark is running here sniffing from the dongle (Wifi2) 

The question being is am I Correctly sniffing the necessary adapter. I see the ICMP payload "test_ping_icmp" when running CMDs from the FnF machine in ap mode. Once the device connects to it the FnF machine sends the raw ICMP payload and I'm able to see the necessary ICMP packet. Again does this mean that the USB dongle is vulnerable to the corresponding CMD being used?

**Comment by D3adP3nguin** [comment]
Also just as an interesting bit of information, when testing on windows the following CMDs cause a BSOD (Blue Screen Of Death) : `./fragattack.py wlan0mon eapol-amsdu I,P --inject wlan2 --ap` & `./fragattack.py wlan0mon eapol-amsdu B,P --inject wlan2 --ap`
The OS error shows up as _`rtwlan.sys failed`_

**Comment by vanhoefm** [comment]
- If you can see the "test_ping_icmp" payload then you know that the Windows 10 device received the ping request. Whether this means the device is vulnerable depends on the specific command: with a simple "ping" command it's normal to see this payload but with a command such as "ping I,P" this indicates a vulnerability. See the README for details.
- BSOD: I've had the same when testing an AWUS036ACH on Windows 10. Which dongle were you testing?

**Comment by D3adP3nguin** [comment]
The device in monitor mode: AWUS036NHA
The device in ap mode: AWUS036ACM

**Comment by vanhoefm** [comment]
To clarify, I'd like to know the network card that you used on Windows 10. In other words, when you got the BSOD, which network card was the Windows 10 computer using?

**Comment by D3adP3nguin** [comment]
I was using my FnF test machine in AP mode. On the windows computer, I had a WUSB6300v2(a wifi dongle) I was testing it via connecting to the AP created by the FnF test machine. The 2 tests that caused the Windows BSOD were:
`eapol-amsdu I,P` && `eapol-amsdu BP`; however the -bad versions of these commands did not cause the BSOD.

**Comment by vanhoefm** [comment]
Thanks for the info!

If you're also willing to share your other test results let me know. That is, you seem to be testing a lot of devices, and making a global overview of results (including yours and others) might be interesting.

**Comment by D3adP3nguin** [comment]
I have tested roughly 25 devices and I'm still getting more and more every day. It would be interesting to create a result sheet with you.

**Comment by D3adP3nguin** [comment]
I'll have to ask my higher-ups if this is permittable, hope you understand. 
Thank you for the amazing support and tool, your research has been something I have been following for many years now thank you.

**Comment by vanhoefm** [comment]
No problem, let me know what they say (my e-mail address is in my papers).
