### ISSUE TITLE
Airmon-ng issue

### ISSUE THREAD

**Issue by D3adP3nguin** [vanhoefm/fragattacks#36]
This is an informative post: 
When using airmong-ng with mt76x2u  NiCs it causes the live OS to crash. I have found an alternative setup so I wanted to share with those who might be running into the same problem 

- sudo ip   link set wlan0 down
- sudo iw wlan0   set monitor control
- sudo ip link   set wlan0 name wlan0mon
- sudo ip link   set wlan0mon up

_Then if you are using 5Ghz do the following_
- iwconfig   wlan0mon freq 5.220G
- iwconfig   wlan0mon channel 44
- You will also want to set your AP's 5Ghz SSID to use channel 44 (5.220G freq)

**Comment by vanhoefm** [comment]
Thanks, I've added a reference to this in the README!
