### ISSUE TITLE
Mixed Key Attacks - PTK rekey issue

### ISSUE THREAD

**Issue by D3adP3nguin** [vanhoefm/fragattacks#37]
When testing the Mixed Key Attacks the test device needs to reissue the PTK key, however, after running this test for a while the device still doesn't re-issue the key. We are not able to manually force the device to re-issue the key (unless there is a good trick you know about). When you test devices with this attack how do you cause the PTK rekey to be issued?

**Comment by vanhoefm** [comment]
On some routers or access points, you can configure when the PTK is refreshed. If it seems impossible to refresh the PTK then it's not possible to perform a mixed key attack against it.

**Comment by vanhoefm** [comment]
Some routers may not have an option to rekey the PTK. In that case, the mixed key attack is not possible.

For the code audit: if the specific device doesn't want to do a PTK rekey, even after various tries to change the configuration, then you can assume that _this device_ is not vulnerable to the mixed key attack.
