### ISSUE TITLE
5Ghz AP Testing

### ISSUE THREAD

**Issue by D3adP3nguin** [vanhoefm/fragattacks#39]
I have had great luck in testing an External NiC card with fragattacks AP mode. However, that was for 2.4Ghz. When I'm now trying to test for the 5Ghz SSID by launching the AP using a 5Ghz Alfa card (AWUS036ACM). When I try to connect the NiC to the AP being broadcasted by the Alfa Card it gets an error message 4way handshake has timed out. Any thoughts on what could be happening or any settings I must change to test 5Ghz in AP mode?

**Comment by vanhoefm** [comment]
Can you try to set up an AP in the 5GHz band using standard Linux software? For instance, using Hostapd or your network manager. That will help to determine whether this issue is specific to my scripts or an issue with setting up a 5GHz AP in general.

**Comment by D3adP3nguin** [comment]
So it ended up being the cipher used by the AP was psk it was CMAC. is there a way to change the cipher used by the fnf toolset to use cmac instead of psk. I resolved this by constantly changing the AP settings til the cipher landed on psk (lol)
