### ISSUE TITLE
UNINITIALIZED→DISABLED AP-DISABLED

### ISSUE THREAD

**Issue by Whitecro** [vanhoefm/fragattacks#45]
I've tried to reconfigure hostapd.conf but the same error appears as the following : 
driver mode  nl80211: deinit ifname-wlan1 disabled_11b_rates-0  nl80211 driver initialization failed.  wlan1: interface state UNINITIALIZED→DISABLED  wlan1: AP-DISABLED  wlan1: CTRL-EVENT-TERMINATING  hostapd_free_hapd_data: Interface wlan1 wasn't started

**Comment by vanhoefm** [comment]
As far as I know, the RTL8187 doesn't support AP mode. This means you cannot use this network card to create an AP (and you can't test clients). You may still be able to test access points by using the test tool in client mode.

You can confirm whether or not the RTL8187 supports AP mode by executing `iw list`.

**Comment by Whitecro** [comment]
I've checked the adapter with iw list and it says that it supported Ap mode

**Comment by vanhoefm** [comment]
Show the full output of `iw list` and show the full output of the test tool (start the test tool using the extra parameter `--debug 2` for extra debug output).

**Comment by Whitecro** [comment]
Wiphy phyo

wiphy index: 0

max # scan SSIDS: 4

max scan IES length: 2285 bytes max #sched scan SSIDS: 0

max # match sets: 0

max #scan plans: 1 max scan plan interval: -1

max scan plan iterations: 0

Retry short limit: 7 Retry long limit: 4

Coverage class: 0 (up to 0m) Device supports RSN-IBSS.

Supported Ciphers:

*WEP40 (00-of-ac:1) WEP104 (00-0f-ac:5)

TKIP (00-0f-ac:2) CCMP-128 (00-0f-ac:4)

CCMP-256 (00-of-ac:10) GCMP-128 (00-0f-ac:8)

GCMP-256 (00-of-ac:9) Available Antennas: TX 0 RX

O

Supported interface modes:

IBSS

managed

monitor

Band 1:

Bitrates (non-HT):

1.0 Mbps

2.0 Mbps

5.5 Mbps

11.0 Mbps

6.0 Mbps

9.0 Mbps

• 12.0 Mbps

* 18.0 Mbps

24.0 Mbps

36.0 Mbps

48.0 Mbps

. 54.0 Mbps

Frequencies:

2412 MHz 2417 MHz [2]

[1] (20.0 dBm) (20.0 dBm)

2422 MHz [3] (20.0 dBm) 2427 MHz [4] (20.0 dBm)

2432 MHz [5] (20.0 dBm) 2437 MHz [6] (20.0 dBm)

2442 MHz (7] (20.0 dBm)

2447 MHz [8] (20.0 dBm • 2452 MHz [9] 20.0 dBm)

2457 MHz [10] (20.0 dBm)

2462 MHz (11) (20.0 dBm) 2467 MHz [12] (20.0 dBm) (no IR)

2472 MHz [13] (20.8 dBm) 2484 MHZ [14] (20.0 dBm) (no IR)

Supported commands:

•new interface set interface

new key start_ap

* start_ap

*new_station

* new_mpath

set_mesh_config

set_bss * authenticate

associate

*deauthenticate

* disassociate

* join_ibss

* join_mesh

* remain_on_channel * set_tx_bitrate_mask

* frame * frame_wait_cancel

*set_wiphy_netns *set_channel

*set_wds_peer probe_client

* set_noack_map

* register_beacons

*start_p2p_device

* set_mcast_rate ✰ connect

disconnect

set_qos_map

set multicast_to_unicast

Supported TX frame types:

IBSS: 0x00 0×10 0×20 0-30 0x40 0×50 0×60 0×70 0x80 0×90 0-30 0xb0 0xc0 0 do
0xeo Oxfo managed: 0x00 0×10 0×20 0-30 0x40 0×50 0×60 0×70 0-80 0x90 0xa0
0xb0 0xc0 0-do Oxeo 0xfo

AP: 0x00 0-10 0x20 0-30 0x40 0×50 0×60 0x700x80 0x90 0xa0 0xb0 0xc0 0 do
0xe0 0xfo AP/VLAN: 0x00 0×10 0×20 0×30 0×40 0×50 0×60 0×70 0-80 0×90 0xa0
0xb0 0xc0 0-do 0xe0 Oxfo

mesh point: 0x00 0x10 0x20 0-30 0x40 0×50 0×60 0x70 0x80 0x90 0-30 0-b0
0xco 0xd0 Oxe0 0-fo * P2P-client: 0x00 0×10 0.20 0x30 0×40 0×50 0×60 0×70
0×80 0×90 0x20 0xb0 0xc0 0xd0 0e0 0-fo

P2P-GO: 0x00 0x10 0×20 0×30 0x40 050 0x60 0x70 0×80 0x90 0xa0 0xb0 0xc0 0
do 0xe0 Oxfo

* P2P-device: 0x00 0×10 0-20 0×30 0x40 0×50 0x60 0x70 0x80 0x90 0-30 0xb0
0xc0 0xd0 0e0 0-fo

Supported RX frame types:

IBSS: 0x40 0xb0 0xc0 exdo

managed: 0x40 0xbe 0xde

AP: 0x00 0.20 0x48 0xa0 0xb0 exco exde * AP/VLAN: 0x80 0-20 0×40 0xa0 Oxbo
0xc0 exde

* mesh point: 0xb0 0xc0 Oxdo

P2P-client: 0x40 0xde

* P2P-GO: 8-80 6-20 040 0xae 8-b0 0xco Oxdohrs

P2P-device: 8x40 8xdo

software interface modes (can always be added): interface combinations are
not supported

✰ monitor

HT Capability overrides:

. MCS : ff ff ff ff ff ff ff ff ff ff

• maximum A-MSDU length

supported channel width

short GT for 40 z

• max A-MPDU Length exponent

min MPDU start spacing

Device supports TX status socket option. Device supports HT-IBSS.

short GI for 40 MHz

max A-MPDU length exponent

* min MPDU start spacing

Device supports TX status socket option.

Device supports HT-IBSS.

Device supports SAE with AUTHENTICATE command

Device supports low priority scan.

Device supports scan flush.

Device supports AP scan.

Device supports per-vif TX power setting

Driver supports full state transitions for AP/GO clients

Driver supports a userspace MPM

Device supports configuring vdev MAC-addr on create.

Supported extended features:

[ RRM ] RRM

* [FILS STA ]: STA FILS (Fast Initial Link Setup) restoring your last brey
ina spat Sove [COM RSSI_LIST ]: multiple COM RSSI_THOLD records MO

[CONTROL PORT_OVER_NL80211 ]: control port over nl80211 SCAN_RANDOM SN 1:
use random sequence numbers in scansum Sometting

[SCAN_MIN_PREQ_CONTENT 1: use probe request with only rate IES in scans
[CAN_REPLACE_PTKO J: can safely replace PTK 0 when rekeying

[EXT KEY_ID 1: Extended Key ID support

a fabris coming 2

from the table you don't

[CONTROL PORT_NO PREAUTH ]: disable pre-auth over nl80211 control port
support

[DEL_IBSS_STA ]: deletion of IBSS station support [SCAN FREQ KHZ ]: scan on
kHz frequency support

[CONTROL PORT_OVER_NL80211_TX_STATUS 1: tx status for nl88211 control port
support


[21:09:04] This is FragAttack version 1.3. [21:09:05] Using interface
monwlane (rtl8187) to inject frames.

[21:09:06] Starting hostapd using: ../hostapd/hostapd -i wlane hostapd.conf
-K nl80211: Could not configure driver mode

nl80211: deinit ifname-wlane disabled_11b_rates-0 se svarevmius rabs, rove
the chickmarkllem la20

nl80211 driver initialization failed. wlane: interface state
UNINITIALIZED-DISABLED

wlane: AP-DISABLED

wlane: CTRL-EVENT-TERMINATING

hostapd_free_hapd_data: Interface wlane wasn't started

[21:09:16] Unable to connect to control interface. Did
hostap/wpa_supplicant start properly? [21:09:16] Try recompiling them using
/build.sh and double-check client.conf and hostapd.conf.

[21:09:16] Closing daemon and cleaning up ...


[21:16:01] This is FragAttack version 1.3. [21:16:01] Using interface
monwlane (rtl8187) to inject frames.

[21:16:01] Starting hostapd using: /hostapd/hostapd -i wlan0 hostapd.conf
-dd-K random: Trying to read entropy from /dev/random

Configuration file: hostapd.conf

ctrl interface group-0

nl80211: Supported cipher 00-0f-ac:1 nl80211: Supported cipher 00-of-ac:5

n180211: Supported cipher 00-0f-ac:2

nl80211: Supported cipher 00-of-ac:4 nl80211: Supported cipher 00-0f-ac:10

nl80211: Supported cipher 08-0f-ac:8

nl80211: Supported cipher 00-0f-ac:9

nl80211: Using driver-based off-channel TX

nl80211: Driver-advertised extended capabilities (default)- hexdump(len-8):
00 00 00 00 00 00 00 40 n180211: Driver-advertised extended capabilities
mask (default) - hexdump(len-5): 00 00 00 00 00 00 00 40

n180211: key_mgmt-8x1ffof enc-0xef auth-0x7 flags-exa40005104b03d0a0 rra
flags-0-10 probe_resp_offloads-0-0 max stations-0 m

ax_remain_on_chan-5000 max_scan_ssids-4

n180211: interface wlane in phy phys

nl80211: Set mode ifindex 3 iftype 3 (AP) nl80211: Failed to set interface
3 to mode 3: -95 (Operation

nl80211: Try mode change after setting interface down

not supported)

n180211: Set mode ifindex 3 iftype 3 (AP) n180211: Failed to set interface
3 to mode 3: -95 (Operation not supported)

nl80211: Interface mode change to 3 from @ failed

nl80211: Could not configure driver mode n180211: deinit ifname-wlane
disabled 11b_rates-0

n188211: Remove monitor interface: refcount-0

netlink: Operstate: ifindex-3 linkmode-0 (kernel-control), operstate-6 (IF
OPER UP)

n180211: Set mode ifindex 3 iftype 2 (STATION) n180211 driver
initialization failed.

hostapd_interface_deinit_free(0x1d02a40) hostapd_interface_deinit free:
num_bss-1 conf→num_bss-1

hostapd_interface_deinit(0x1d02a40) wlane: interface state UNINITIALIZED
DISABLED

hostapd_bss_deinit: deinit bss wlane

wlano: AP-DISABLED

hostapd_cleanup(hapd-0-1d036a0 (wlane))

wland: CTRL-EVENT-TERMINATING

hostapd_free_hapd_data: Interface wlane wasn't started to rest

hostapd_interface deinit free: driver-(nil) drv_priv-(nil)→ hapd_deinit

hostapd interface free(0x1d02a40) hostapd interface free: free hapd
8x1d036a0

hostapd_cleanup_iface(0x1d02a49)

hostapd_cleanup iface partial (@=1d02a40)

hostapd_cleanup iface: free iface-8x1d02a40

[21:16:11] Uable to connect to control interface. Did hosts/wo supplicant
start properly? [21:16:11] Try recompiling then walng /build.sh and
double-check client.conf and hostapd.conf.

[21:16:11] Closing daemon and cleaning up...

**Comment by vanhoefm** [comment]
> Supported interface modes:
> IBSS
> managed
> monitor

Unfortunately, this means your network card doesn't support AP mode. For contrast, [here](https://deviwiki.com/wiki/TP-LINK_TL-WN823N_v1) is the output of a device that does support AP mode.
