### ISSUE TITLE
Send WPA2 EAPOL handshake as Data Frames

### ISSUE THREAD

**Issue by billysmithde** [vanhoefm/fragattacks#5]
Great work and nice toolset.

I have a really old 802.11b/g-only client that I want to test but I can't get through the WPA2 handshake.

I suspect that it is due to the EAPOL frames from the tool in AP mode (--ap) are sent as type_subtype 0x28, or _QoS Data_.  I configured hostapd.conf to disable 11n and wmm; when I run hostapd with that config file from CLI in the provided Live Image, I get expected results in that EAPOL frames are _Data_ type, not _QoS Data_ as determined from OTA packet capture.  However, that same config, when used with the tool, always produces type _QoS Data_ across the 8 adapters tested locally.  When I run the tool with debug 2, it looks like the WPA2 handshake is done via injected packets with subtype 8:  
   
```
[02:02:38] Station: setting BSS MAC address e2:de:17:12:8a:72
wlan2: EAPOL-TX 00:00:01:36:af:f7 
....
[02:02:38] Action.StartAuth
[02:02:38] [Injected packet] <Dot11  **subtype=8 type=Data** FCfield=from-DS addr1=00:00:01:36:af:f7 addr2=e2:de:17:12:8a:72 addr3=e2:de:17:12:8a:72 SC=256 |<Dot11QoS  TID=1 |<LLC  dsap=0xaa ssap=0xaa ctrl...
```

Is there an option to select the type of EAPOL frame injected?

**Comment by vanhoefm** [comment]
There is currently no option to send all frames as normal Data frames. I'll check later today whether this can be quickly added.

**Comment by vanhoefm** [comment]
You can now use the `--no-qos` parameter. This will assure all data frames are sent as normal data frames. This option is experimental, it may break some tests (meaning the tool may say that a device is secure even though it's actually vulnerable).
