### ISSUE TITLE
Error to start fake access point

### ISSUE THREAD

**Issue by faizanff** [vanhoefm/fragattacks#51]
hostapd /root/Downloads/hostapd.conf
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan0 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan0: interface state UNINITIALIZED->DISABLED
wlan0: AP-DISABLED 
wlan0: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan0 wasn't started

**Comment by vanhoefm** [comment]
Your network card probably doesn't support access point mode.
