### ISSUE TITLE
research/client.conf configuration problem

### ISSUE THREAD

**Issue by hector2007ss** [vanhoefm/fragattacks#52]
There are many contents in research/client.conf. As a wifi beginner, I want to know which contents in research/client.conf need to be modified for the AP I need to test.

**Comment by vanhoefm** [comment]
The provided file contains 4 example network profiles. It will connect to the first network that matches one of those profiles. So pick the profile that best matches the network you want to test (WPA2 vs WPA3, home vs enterprise) and then edit that profile.

Google for more information. Example resulting links:
- https://linuxhint.com/how-to-use-wpa-supplicant/
- https://getocean.vercel.app/docs/wifi-wpa-supplicant
- https://wiki.archlinux.org/title/wpa_supplicant

Also see https://github.com/vanhoefm/fragattacks/blob/master/wpa_supplicant/wpa_supplicant.conf for an example of all possible parameters. But that will probably be too detailed for you at this point.
