### ISSUE TITLE
How to run the script for IoT client in which ICMP/PING is disabled

### ISSUE THREAD

**Issue by pococ31** [vanhoefm/fragattacks#53]
on executing the command `./fragattack.py wlan0 --ap ping` the test fails. Later I found that the IoT client doesn't support `ping/ICMP`. How to run fragattack scripts on these types of IoT clients ?

**Comment by vanhoefm** [comment]
This is documented at
https://github.com/vanhoefm/fragattacks/blob/master/README.md#93-no-icmp-support

Ideally you use ICMP though, that has been tested the most and is the most
reliable.

**Comment by pococ31** [comment]
Thank you so much. It works perfectly, I tried with various devices. Thank you.
