### ISSUE TITLE
Is it possible that these vulnerabilities exist on devices without the (AES -) CCMP encryption?

### ISSUE THREAD

**Issue by hector2007ss** [vanhoefm/fragattacks#54]
Is it possible that these vulnerabilities exist on devices without the  (AES -) CCMP encryption?

**Comment by vanhoefm** [comment]
See https://www.fragattacks.com/#tkip and https://www.fragattacks.com/#wep

**Comment by hector2007ss** [comment]
Encryption algorithms GCMP are also not supported, so is it possible that these vulnerabilities exist on devices with GCMP encryption?

**Comment by vanhoefm** [comment]
These questions are also covered in the paper. Search for the term GCMP.

**Comment by hector2007ss** [comment]
According to my understanding, if vulnerabilities are discovered through testing according to the method of this project, whether using CCMP or GCMP, these attacks can be implemented. Is this correct?

**Comment by vanhoefm** [comment]
Ah, this project specifically tests using CCMP only. There's a good chance
that if an implementation is vulnerable when using CCMP (so when this tool
says an implementation is vulnerable) that it will also be vulnerable when
using GCMP. But the only way to be sure that an implementation is also
vulnerable when using GCMP, is to extend this tool to also support GCMP.

Op wo 17 mei 2023 om 11:38 schreef hector2007ss ***@***.***>:
