### ISSUE TITLE
New Vulnerability Notice for ExtremeNetworks 

### ISSUE THREAD

**Issue by laurenta-exer** [vanhoefm/fragattacks#6]
Hi,

Just to let you know that ExtremeNetworks has also published an advisory : 
https://extremeportal.force.com/ExtrArticleDetail?an=000095779&_ga=2.35758688.1123975861.1621101663-317372635.1620859085

Thanks for all the papers you wrote on Wi-Fi security ;)

Regards,
Laurent Asselin.

**Comment by vanhoefm** [comment]
Thanks! The link has been added.
