### ISSUE TITLE
Microsoft DNS Service Changes

### ISSUE THREAD

**Issue by abiurrunc** [vanhoefm/fragattacks#7]
Hello all.

What changes do I have to make to my Microsoft DNS service servers?

Many Thanks and have a nice week.

**Comment by vanhoefm** [comment]
Not sure what you mean by this question. The vulnerabilities affect Wi-Fi. Attacks against clients can be slightly mitigated by configuring a static DNS server in clients.

**Comment by abiurrunc** [comment]
Hello vanhoefm.
The answer is perfect, the company where I'm working told me that I have to make changes on my DNS server to avoid fragattacs.
With you answer I know that I can not make changes on Microsoft DNS services.
Many thanks and have a nice week.

**Comment by vanhoefm** [comment]
Ah I see, thanks for clarifying.

**Comment by abiurrunc** [comment]
Thanks to you for your answer.
